x=int(input("enter first number"))
y=int(input("enter second number"))
et=(x==y)
net=(x!=y)
get=(x>y)
let=(x<=y)
gt=(x>y)
lt=(x<y)
print("equal to" ,et)
print("not equal to" ,net)
print("greater than or equal to" ,get)
print("lessthan or equal to" ,let)
print("greater than" ,gt)
print("less than" ,lt)